name: lutris
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/kenderipa/My-workbench/main/lutris-junest.sh
        chmod a+x ./lutris-junest.sh
        ./lutris-junest.sh
        mkdir dist
        mv *AppImage dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: lutris-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: lutris-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Test lutris
            automatic_release_tag: test-lutris
            prerelease: false
            draft: false
            files: |
              lutris-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
