name: Test release
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
    - id: setVariables
    - if: always()
      run: |
        input=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)
        echo "matrix=$input" >> $GITHUB_OUTPUT
      env:
          input: ${{ inputs.input_json }}
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
         
  release:
      permissions: write-all
      runs-on: ubuntu-latest
      strategy:
        matrix: ${{ fromJson(needs.setup.outputs.matrix) }}

      steps:
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: AppMan ${{ inputs.input_json }}
            automatic_release_tag: ${{ inputs.input_json }}
            prerelease: false
            draft: false
            repo_token: ${{ secrets.GITHUB_TOKEN }}
