name: Test tag
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on: 
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - id: setVariables
        run: |
          input=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)
          echo "matrix=$input" >> $GITHUB_OUTPUT
          TAG=${{ matrix.tag }}
          echo "AM_VERSION=$TAG" >> $GITHUB_ENV
        env:
          input: ${{ inputs.input_json }}
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
     
  release:
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - name: release
          uses: ncipollo/release-action@v1.12.0
          with:
            name: AppMan ${{ env.AM_VERSION }}
            tag: ${{ env.AM_VERSION }}
            prerelease: false
            draft: false
            token: ${{ secrets.GITHUB_TOKEN }}

