name: Test release
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        echo "APPMAN_TAG=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Aisleriot-x86_64.AppImage
        path: ${{ env.APPMAN_TAG }}
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: AppMan ${{ env.APPMAN_TAG }}
            automatic_release_tag: ${{ env.APPMAN_TAG }}
            prerelease: false
            draft: false
            repo_token: ${{ secrets.GITHUB_TOKEN }}
