name: Test release
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        VERSION=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)
        git commit --all --message "$VERSION"
        git tag $VERSION
        git push
        git push --tags

        gh release create $VERSION --generate-notes --title $VERSION --verify-tag
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: AppMan ${{ env.VERSION }}
            tag: ${{ env.VERSION }}
            prerelease: false
            draft: false
            repo_token: ${{ secrets.GITHUB_TOKEN }}
