name: Test Release
on:
  workflow_call:
    inputs:
      input_json:
        required: true
        type: string
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check version
      if: always()
      run: |
        version=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)
        echo "VERSION=$version" >> $GITHUB_ENV
       
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - name: release
          uses: ncipollo/release-action@v1.12.0
          with:
            name: AppMan ${{ env.VERSION }}
            tag: ${{ env.VERSION }}
            prerelease: false
            draft: false
            token: ${{ secrets.GITHUB_TOKEN }}

