name: Test tag
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        echo "latest_tag=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)" >> "$GITHUB_ENV"

    - name: release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: AppMan ${{ env.latest_tag }}
        automatic_release_tag: ${{ github.ref }}
        prerelease: false
        draft: false
        repo_token: ${{ secrets.GITHUB_TOKEN }}
