name: Test tag
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on: 
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: setVariables
        run: |
          version=$(wget -q https://api.github.com/repos/ivan-hc/AM-Application-Manager/releases/latest -O - | grep tag_name | cut -d '"' -f 4)
          echo "AM_VERSION=$version" >> $GITHUB_ENV
      
  release:
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - name: release
          uses: ncipollo/release-action@v1.12.0
          with:
            name: AppMan ${{ env.AM_VERSION }}
            tag: ${{ env.AM_VERSION }}
            prerelease: false
            draft: false
            token: ${{ secrets.GITHUB_TOKEN }}

